global using ElasticsearchDemoCore2026.Entities;
global using ElasticsearchDemoCore2026.Interfaces;
global using ElasticsearchDemoCore2026.Services;
global using ElasticsearchDemoCore2026.Repositories;
global using ElasticsearchDemoCore2026.Elasticsearch;
global using ElasticsearchDemoCore2026.Models;
global using ElasticsearchDemoCore2026.DTOs;
global using ElasticsearchDemoCore2026.Common;